var a = require("./test.html");
var b = require('./test.html');
var c = require(`./test.html`);
var a2 = require("test.html");
var b2 = require('test.html');
var c2 = require(`test.html`);
var d = require("test.html"); var e = require(`test.html`);
var f = require("c:\\test\\test.html");
var g = require("./test/test.html");
var h = require("./test.htm");
var i = require("test");
//var j = require("test.html");
