var a = require("./test.html");
var b = require('./test.html');
var c = require(`./test.html`);
var d = require("test.html");
var e = require('test.html');
var f = require(`test.html`);
var g = require("test.html"); var h = require(`test.html`);
var i = require("c:\\test\\test.html");
var j = require("./test/test.html");
var k = require("./test.htm");
var l = require("test");
//var m = require("test.html");
